name: Deploy to S3 using OIDC Role

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Allow GitHub to generate an OIDC token
      contents: read   # Allow GitHub to read repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository's code

      - name: Configure AWS credentials from OIDC
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::074460675775:role/github-oidc-role
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Empty S3 bucket
        run: aws s3 rm s3://githubactionss3bucket --recursive

      - name: Sync S3 bucket
        run: aws s3 sync website/ s3://githubactionss3bucket --acl public-read
